ALTER TABLE game ADD COLUMN name VARCHAR(100) NOT NULL DEFAULT 'Unnamed Game';
ALTER TABLE game ADD COLUMN max_players INT NOT NULL DEFAULT 5;
ALTER TABLE game ADD COLUMN created_by_user_id BIGINT REFERENCES app_user(id) ON DELETE SET NULL;
